#name: Deploy on Push

#on:
 # push:
  #  branches:
   #   - main

#jobs:
 # build:
  #  runs-on: self-hosted

   # strategy:
    #  matrix:
     #   node-version: [25.5.1]

    #steps:
     # - uses: actions/checkout@v4
      #- name: Use Node.js ${{ matrix.node-version }}
       # uses: actions/setup-node@v4
        #with:
         # node-version: ${{ matrix.node-version }}
          #cache: "npm"

      #- name: Install dependencies
       # run: npm ci

     # - name: rsync deployments
      #  uses: burnett01/rsync-deployments@5.1
       # with:
        #  switches: -avzr --delete
         # path: ./*
          #remote_path: /
#          remote_host: ec2-13-51-53-216.eu-north-1.compute.amazonaws.com
 #         remote_user: ec2-user
  #        remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
